 platform :ios, '10.0'

target 'BaiSiBuDeiJie' do
 pod 'AFNetworking', '~> 3.1.0'
 pod 'MJExtension', '~> 3.0.13'
 pod 'SDWebImage+ExtensionSupport', '~> 3.7.1.2'
 pod 'SVProgressHUD', '~> 2.0.3'
 pod 'DACircularProgress', '~> 2.3.1'
 pod 'MJRefresh', '~> 3.1.12'
end
